default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: rails-recipe-application_development

test:
  <<: *default
  database: rails-recipe-application_test
